apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: full-cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch-name
      type: string
      default: main
    - name: image-name
      type: string
      default: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/myapp

  workspaces:
    - name: shared-workspace

  tasks:

    # 1. CLONE REPO
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.branch-name)"
      workspaces:
        - name: output
          workspace: shared-workspace

    # 2. INSTALL + LINT + TEST
    - name: test-app
      runAfter: ["clone-repo"]
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: install-deps
            image: python:3.9-slim
            workingDir: /workspace/source
            script: |
              pip install --upgrade pip
              pip install flake8 nose

          - name: lint
            image: python:3.9-slim
            workingDir: /workspace/source
            script: |
              pip install flake8
              flake8 .

          - name: test
            image: python:3.9-slim
            workingDir: /workspace/source
            script: |
              pip install nose
              nosetests || true
      workspaces:
        - name: source
          workspace: shared-workspace
